In [2]:
# !pip install transformers

In [21]:
from transformers import pipeline
import pandas as pd

In [22]:
twitter_data=pd.read_csv("/content/twitter_sentiment_analysis.csv")

In [23]:
twitter_data.head()

   Unnamed: 0  ...              user_id
0           0  ...  1045700375997747203
1           1  ...  1222466541058289665
2           2  ...  1332714745871421443
3           3  ...  1222466541058289665
4           4  ...  1222466541058289665

[5 rows x 5 columns]

In [24]:
twitter_data_filtered_data=twitter_data[["tweet_text"]]

In [25]:
twitter_data_filtered_data.head()

                                          tweet_text
0  #Transport Exchange Group: Data &amp; Logistic...
1  #FEATURED #COURSES\nThe C# Basics from Scratch...
2  NEED a JOB?\nSign up now https://t.co/o7lVlsl7...
3  #FEATURED #COURSES\nThe Complete MySQL from Sc...
4  #FEATURED #COURSES\nThe Complete Microsoft SQL...

In [26]:
tweet_data_list=twitter_data_filtered_data.tweet_text.to_list()
len(tweet_data_list)

100

In [27]:
sentiment_classifier = pipeline('sentiment-analysis')

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english)

In [28]:
sentiment_label = [i for i in sentiment_classifier(tweet_data_list)]
sentiment_label

[{'label': 'POSITIVE', 'score': 0.9244814515113831},
 {'label': 'NEGATIVE', 'score': 0.9950568675994873},
 {'label': 'NEGATIVE', 'score': 0.9986178874969482},
 {'label': 'NEGATIVE', 'score': 0.9970988035202026},
 {'label': 'NEGATIVE', 'score': 0.9970759153366089},
 {'label': 'NEGATIVE', 'score': 0.9995916485786438},
 {'label': 'POSITIVE', 'score': 0.9488546848297119},
 {'label': 'NEGATIVE', 'score': 0.5447470545768738},
 {'label': 'POSITIVE', 'score': 0.6564761996269226},
 {'label': 'NEGATIVE', 'score': 0.9985777139663696},
 {'label': 'NEGATIVE', 'score': 0.8992231488227844},
 {'label': 'NEGATIVE', 'score': 0.9980337023735046},
 {'label': 'NEGATIVE', 'score': 0.9968830347061157},
 {'label': 'NEGATIVE', 'score': 0.9963206052780151},
 {'label': 'NEGATIVE', 'score': 0.9947419166564941},
 {'label': 'NEGATIVE', 'score': 0.5605816841125488},
 {'label': 'NEGATIVE', 'score': 0.7538641691207886},
 {'label': 'NEGATIVE', 'score': 0.9949683547019958},
 {'label': 'NEGATIVE', 'score': 0.9923068881034851},
 {'label': 'NEGATIVE', 'score': 0.9453431367874146},
 {'label': 'NEGATIVE', 'score': 0.997416615486145},
 {'label': 'NEGATIVE', 'score': 0.9968299269676208},
 {'label': 'NEGATIVE', 'score': 0.9508503079414368},
 {'label': 'NEGATIVE', 'score': 0.9968330264091492},
 {'label': 'NEGATIVE', 'score': 0.689440131187439},
 {'label': 'NEGATIVE', 'score': 0.6235419511795044},
 {'label': 'NEGATIVE', 'score': 0.9984924793243408},
 {'label': 'NEGATIVE', 'score': 0.9968649744987488},
 {'label': 'NEGATIVE', 'score': 0.9987572431564331},
 {'label': 'NEGATIVE', 'score': 0.940622091293335},
 {'label': 'POSITIVE', 'score': 0.8660646080970764},
 {'label': 'NEGATIVE', 'score': 0.9968451261520386},
 {'label': 'NEGATIVE', 'score': 0.9974678754806519},
 {'label': 'NEGATIVE', 'score': 0.8527464270591736},
 {'label': 'NEGATIVE', 'score': 0.75176602602005},
 {'label': 'NEGATIVE', 'score': 0.9911124110221863},
 {'label': 'NEGATIVE', 'score': 0.9965887069702148},
 {'label': 'NEGATIVE', 'score': 0.8859938979148865},
 {'label': 'NEGATIVE', 'score': 0.9986394047737122},
 {'label': 'NEGATIVE', 'score': 0.9925262928009033},
 {'label': 'NEGATIVE', 'score': 0.9967772364616394},
 {'label': 'NEGATIVE', 'score': 0.9911824464797974},
 {'label': 'NEGATIVE', 'score': 0.9937491416931152},
 {'label': 'NEGATIVE', 'score': 0.8814862966537476},
 {'label': 'NEGATIVE', 'score': 0.5999096035957336},
 {'label': 'POSITIVE', 'score': 0.6857582926750183},
 {'label': 'NEGATIVE', 'score': 0.9970784187316895},
 {'label': 'NEGATIVE', 'score': 0.9887434244155884},
 {'label': 'NEGATIVE', 'score': 0.9877888560295105},
 {'label': 'NEGATIVE', 'score': 0.971390962600708},
 {'label': 'NEGATIVE', 'score': 0.9891830682754517},
 {'label': 'NEGATIVE', 'score': 0.9990932941436768},
 {'label': 'NEGATIVE', 'score': 0.9692719578742981},
 {'label': 'NEGATIVE', 'score': 0.995435893535614},
 {'label': 'NEGATIVE', 'score': 0.8416615128517151},
 {'label': 'NEGATIVE', 'score': 0.9955452680587769},
 {'label': 'NEGATIVE', 'score': 0.9851092100143433},
 {'label': 'NEGATIVE', 'score': 0.9952520132064819},
 {'label': 'NEGATIVE', 'score': 0.9896515011787415},
 {'label': 'NEGATIVE', 'score': 0.9985523819923401},
 {'label': 'NEGATIVE', 'score': 0.8755894303321838},
 {'label': 'POSITIVE', 'score': 0.9744155406951904},
 {'label': 'NEGATIVE', 'score': 0.9967693090438843},
 {'label': 'NEGATIVE', 'score': 0.9892261624336243},
 {'label': 'NEGATIVE', 'score': 0.9103711843490601},
 {'label': 'NEGATIVE', 'score': 0.9975705742835999},
 {'label': 'NEGATIVE', 'score': 0.9969835877418518},
 {'label': 'NEGATIVE', 'score': 0.6979497671127319},
 {'label': 'NEGATIVE', 'score': 0.9303507208824158},
 {'label': 'NEGATIVE', 'score': 0.6277196407318115},
 {'label': 'NEGATIVE', 'score': 0.8579127192497253},
 {'label': 'NEGATIVE', 'score': 0.9971326589584351},
 {'label': 'NEGATIVE', 'score': 0.9969436526298523},
 {'label': 'NEGATIVE', 'score': 0.9972215890884399},
 {'label': 'NEGATIVE', 'score': 0.9955189228057861},
 {'label': 'POSITIVE', 'score': 0.9808752536773682},
 {'label': 'NEGATIVE', 'score': 0.9471703767776489},
 {'label': 'POSITIVE', 'score': 0.7296635508537292},
 {'label': 'NEGATIVE', 'score': 0.9855055212974548},
 {'label': 'POSITIVE', 'score': 0.9521287083625793},
 {'label': 'NEGATIVE', 'score': 0.995378851890564},
 {'label': 'NEGATIVE', 'score': 0.9974011182785034},
 {'label': 'NEGATIVE', 'score': 0.9969727993011475},
 {'label': 'POSITIVE', 'score': 0.9968369007110596},
 {'label': 'NEGATIVE', 'score': 0.9968980550765991},
 {'label': 'NEGATIVE', 'score': 0.7451531887054443},
 {'label': 'NEGATIVE', 'score': 0.9986200332641602},
 {'label': 'NEGATIVE', 'score': 0.8593321442604065},
 {'label': 'NEGATIVE', 'score': 0.9953750967979431},
 {'label': 'NEGATIVE', 'score': 0.9974203109741211},
 {'label': 'POSITIVE', 'score': 0.7150473594665527},
 {'label': 'NEGATIVE', 'score': 0.9969261288642883},
 {'label': 'POSITIVE', 'score': 0.9989559650421143},
 {'label': 'NEGATIVE', 'score': 0.9968873858451843},
 {'label': 'NEGATIVE', 'score': 0.6170359253883362},
 {'label': 'POSITIVE', 'score': 0.8338263034820557},
 {'label': 'NEGATIVE', 'score': 0.9997424483299255},
 {'label': 'NEGATIVE', 'score': 0.9132732152938843},
 {'label': 'NEGATIVE', 'score': 0.9957389831542969},
 {'label': 'NEGATIVE', 'score': 0.9688323736190796}]

In [29]:
sentiment_dataframe_list=[sentiment_label[i]['label'] for i in range(len(sentiment_label))]
sentiment_dataframe_list

['POSITIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'POSITIVE',
 'NEGATIVE',
 'POSITIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'POSITIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'POSITIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'POSITIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'POSITIVE',
 'NEGATIVE',
 'POSITIVE',
 'NEGATIVE',
 'POSITIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'POSITIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'POSITIVE',
 'NEGATIVE',
 'POSITIVE',
 'NEGATIVE',
 'NEGATIVE',
 'POSITIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE',
 'NEGATIVE']

In [30]:
sentiment_dataFrame=pd.DataFrame(sentiment_dataframe_list,columns={"sentiment"})
sentiment_dataFrame.head()

  sentiment
0  POSITIVE
1  NEGATIVE
2  NEGATIVE
3  NEGATIVE
4  NEGATIVE

In [31]:
data_tweet_final=pd.concat([twitter_data_filtered_data,sentiment_dataFrame],axis=1)
data_tweet_final.head()

                                          tweet_text sentiment
0  #Transport Exchange Group: Data &amp; Logistic...  POSITIVE
1  #FEATURED #COURSES\nThe C# Basics from Scratch...  NEGATIVE
2  NEED a JOB?\nSign up now https://t.co/o7lVlsl7...  NEGATIVE
3  #FEATURED #COURSES\nThe Complete MySQL from Sc...  NEGATIVE
4  #FEATURED #COURSES\nThe Complete Microsoft SQL...  NEGATIVE